SELECT WORKER_TITLE FROM TITLE WHERE WORKER_ID_REF=(SELECT WORKER_ID FROM WORKER WHERE WORKER_ID=1);
SELECT WORKER_ID FROM WORKER WHERE WORKER_ID=1;
SELECT * FROM TITLE;
select * from worker;
SELECT WORKER_TITLE FROM TITLE WHERE WORKER_ID_REF=( SELECT WORKER_ID FROM WORKER WHERE LAST_NAME='Ansari');
-- BETWEEN QUERY
SELECT* FROM WORKER WHERE SALARY BETWEEN 20000 AND 90000;
USE ORG;
-- IS NULL
SELECT FIRST_NAME FROM WORKER WHERE FIRST_NAME IS NOT NULL;
SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%i_';
(SELECT FIRST_NAME FROM WORKER ORDER BY SALARY DESC);
SELECT DISTINCT DEPARTMENT FROM WORKER;
SELECT DISTINCT DEPARTMENT FROM WORKER;
SELECT DEPARTMENT,SUM(SALARY) FROM WORKER GROUP BY DEPARTMENT;

create table loan(
	ACCOUNT_ID INT NOT NULL PRIMARY KEY UNIQUE,
    ACCOUNT_BALANCE INT DEFAULT 2500 NOT NULL,
    FNAME CHAR(50)
);
SELECT * FROM LOAN;
ALTER TABLE LOAN ADD INTEREST FLOAT NOT NULL DEFAULT (2/100);
ALTER TABLE LOAN MODIFY INTEREST DOUBLE;
ALTER TABLE LOAN ADD LOAN_AMT INT NOT NULL;
ALTER TABLE LOAN MODIFY LOAN_AMT DOUBLE;
ALTER TABLE LOAN CHANGE LOAN_AMT LOAN_AMOUNT INT(255);
desc LOAN;
SELECT * FROM LOAN;
ALTER TABLE LOAN ADD COLUMN EXTRA_PAYER CHAR(25);
ALTER TABLE LOAN DROP COLUMN EXTRA_PAYER;
CREATE TABLE ACCOUNT (
	ACCOUNT_ID INT NOT NULL PRIMARY KEY
);
USE ORG;
CREATE TABLE AWE_1(NAME1 CHAR(2),NUMBER1 INT);
CREATE TABLE AWE_2(NAME1 CHAR(2),NUMBER1 INT);
INSERT INTO AWE_1 VALUES('A',1),('B',2),('C',3);
INSERT INTO AWE_2 VALUES('A',1),('C',3),('D',4);
SELECT * FROM AWE_1;
SELECT * FROM AWE_2;
-- DEMONSTARTION OF JOIN 
SELECT * FROM AWE_1 UNION SELECT * FROM AWE_2;
UPDATE AWE_1 set NUMBER1=2 WHERE  NAME1='A';
SELECT * FROM WORKER WHERE DEPARTMENT ="Admin";
SELECT * FROM WORKER WHERE DEPARTMENT NOT IN ('HR','Admin');
SELECT * FROM AWE_1;
SELECT * FROM WORKER;
-- Using Limit Clause
-- SELECT * FROM TABLE WHERE COND LIMIT NO OF RECORDS
Select * from Worker WHERE SALARY>1000 LIMIT 3;
USE ORG;
SELECT * FROM WORKER;
-- TO DISPLAY THE COLUMN NAME AS DEFAULT NAME OF COLUMN NOT GIVEN
SELECT MAX(SALARY) AS GPR FROM WORKER;
-- SELECT THE WORKER WITH HIGEST SALARY
SELECT * FROM WORKER ORDER BY SALARY DESC LIMIT 1;
SELECT MAX(SALARY) AS SALARY,FIRST_NAME from WORKER GROUP BY SALARY,FIRST_NAME;
-- SUB Query
SELECT FIRST_NAME FROM WORKER WHERE SALARY=(SELECT MAX(SALARY) FROM WORKER);
-- Count total number of rows in product table 
SELECT COUNT(*) AS COUNTCOLUMN FROM WORKER;